### ISSUE TITLE
Configure power to the FRC Radio

### ISSUE THREAD

**Issue by preuss812** [preuss812/FRC_2016#1]
- New Radio uses the same plug connector, but DIFFERENT voltage than last year

Heads Up: While the OM5P-AN uses the same power plug as the DAP1522, it takes a 12V input instead of the 5V input of the D-Link. This means that it DOES NOT plug into the port on the VRM labeled "Radio Power", instead use the 12V 2A connection on the VRM. See the Wiring the 2016 FRC Control System document for more details.

https://wpilib.screenstepslive.com/s/4485/m/13503/l/144971?data-resolve-url=true&data-manual-id=13503#Radio-Power-and-Ethernet

**Comment by dkoneill** [comment]
Radio installed on the protobot.
Power switched to 12v/3a
Students verified voltage with multimeter
