### ISSUE TITLE
Install the FRC 2016 Update Suite

### ISSUE THREAD

**Issue by preuss812** [preuss812/FRC_2016#3]
https://wpilib.screenstepslive.com/s/4485/m/13503/l/144150-installing-the-frc-2016-update-suite-all-languages
- Need the username and password for the NI account (see dan)
- Need the Serial # from the DVD that came in the kit of parts

**Comment by dkoneill** [comment]
M81X08388

**Comment by dkoneill** [comment]
FRC 2016 update completed.
