### ISSUE TITLE
Update Firmware on  Pneumatics Control Module and Power Distribution Panel

### ISSUE THREAD

**Issue by preuss812** [preuss812/FRC_2016#8]
https://wpilib.screenstepslive.com/s/4485/m/13503/l/216217-updating-and-configuring-pneumatics-control-module-and-power-distribution-panel

**Comment by dkoneill** [comment]
Updated on protobot.
Need to update on production bot.

**Comment by dkoneill** [comment]
Production robot PCM and PDU updated.
